version: '3'

services:
  database_ignite:
    image: postgres
    container_name: nestjs_prisma
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=nestjs
      - POSTGRES_PASSWORD=nestjs
      - POSTGRES_DB=nestjs
    volumes:
      - pgdata:/data/postgres
    networks:
      - teste-network

volumes:
  pgdata:
    driver: local
networks:
  teste-network:
